const assignmentRouter = require('./assignment');
const assignmentQuestionRouter = require('./assignmentQuestion');
const accountRouter = require('./account');
const classRouter = require('./class');
const classAssignmentRouter = require('./classAssignment');
const classTopicRouter = require('./classTopic');
const gradeRouter = require('./grade');
const questionRouter = require('./question');
const roleRouter = require('./role');
const skillRouter = require('./skill');
const skillAssignmentRouter = require('./skillAssignment');
const standardRouter = require('./standard');
const studentRouter = require('./student');
const studentAssignmentRouter = require('./studentAssignment');
const studentTopicRouter = require('./studentTopic');
const topicRouter = require('./topic');

const route = (app) => {
    app.use('/assignment', assignmentRouter);
    app.use('/assignment-question', assignmentQuestionRouter);
    app.use('/account', accountRouter);
    app.use('/class', classRouter);
    app.use('/class-assignment', classAssignmentRouter);
    app.use('/class-topic', classTopicRouter);
    app.use('/grade', gradeRouter);
    app.use('/question', questionRouter);
    app.use('/role', roleRouter);
    app.use('/skill', skillRouter);
    app.use('/skill-assignment', skillAssignmentRouter);
    app.use('/standard', standardRouter);
    app.use('/student', studentRouter);
    app.use('/student-assignment', studentAssignmentRouter);
    app.use('/studentTopic', studentTopicRouter);
    app.use('/topic', topicRouter);
};
module.exports = route;
