const assignmentRouter = require('./assignment');
const assignmentQuestionRouter = require('./assignmentQuestion');
const accountRouter = require('./account');
const classRouter = require('./class');
const classAssignmentRouter = require('./classAssignment');
const classTopicRouter = require('./classTopic');
const gradeRouter = require('./grade');
const notificationContentRouter = require('./notificationContent');
const notificationRoomRouter = require('./notificationRoom');
const parentRouter = require('./parent');
const questionRouter = require('./question');
const roleRouter = require('./role');
const skillRouter = require('./skill');
const skillAssignmentRouter = require('./skillAssignment');
const standardRouter = require('./standard');
const studentRouter = require('./student');
const studentAssignmentRouter = require('./studentAssignment');
const studentQuestionRouter = require('./studentQuestion');
const studentSkillRouter = require('./studentSkill');
const studentTopicRouter = require('./studentTopic');
const teacherAssignmentRouter = require('./teacherAssignment');
const teacherQuestionRouter = require('./teacherQuestion');
const topicRouter = require('./topic');
const fileRouter = require('./file');

const route = (app) => {
    app.use('/api/assignment', assignmentRouter);
    app.use('/api/assignment-question', assignmentQuestionRouter);
    app.use('/api/account', accountRouter);
    app.use('/api/class', classRouter);
    app.use('/api/class-assignment', classAssignmentRouter);
    app.use('/api/class-topic', classTopicRouter);
    app.use('/api/grade', gradeRouter);
    app.use('/api/notification-content', notificationContentRouter);
    app.use('/api/notification-room', notificationRoomRouter);
    app.use('/api/parent', parentRouter);
    app.use('/api/question', questionRouter);
    app.use('/api/role', roleRouter);
    app.use('/api/skill', skillRouter);
    app.use('/api/skill-assignment', skillAssignmentRouter);
    app.use('/api/standard', standardRouter);
    app.use('/api/student', studentRouter);
    app.use('/api/student-assignment', studentAssignmentRouter);
    app.use('/api/student-question', studentQuestionRouter);
    app.use('/api/student-skill', studentSkillRouter);
    app.use('/api/student-topic', studentTopicRouter);
    app.use('/api/teacher-assignment', teacherAssignmentRouter);
    app.use('/api/teacher-question', teacherQuestionRouter);
    app.use('/api/topic', topicRouter);
    app.use('/api/file', fileRouter);
};
module.exports = route;
